#!/bin/bash
# SENTINEL — Quick Start Runner
# Run this from the root neurvinial directory

echo "🚀 SENTINEL Full Stack Starting..."
echo ""
echo "============================================"
echo "Opening 2 terminal windows..."
echo "============================================"
echo ""
echo "TERMINAL 1 (Backend on port 3000):"
echo "  cd /c/Users/PANDAN/OneDrive/Desktop/neurvinial"
echo "  npm start"
echo ""
echo "TERMINAL 2 (Frontend on port 5173):"
echo "  cd /c/Users/PANDAN/OneDrive/Desktop/neurvinial/frontend"
echo "  npm run dev"
echo ""
echo "============================================"
echo "Then visit: http://localhost:5173"
echo "============================================"
echo ""
echo "To stop:"
echo "  - Backend: Ctrl+C"
echo "  - Frontend: Ctrl+C"
echo ""
